### ISSUE TITLE
TODO before launch

### ISSUE THREAD

**Issue by mathiassoeholm** [mathiassoeholm/lou-website#2]
- [ ] Replace `LOUISE_EMAIL` in Netlify with Louises e-mail
- [ ] Set Global SEO settings on Dato CMS
- [ ] Delete temporary articles, references and comments
